### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by jonbarrow**
Update the license to AGPLv3

Need permission from the following contributors to continue:

- [x] @andreluis034
- [x] @mrjvs  
- [x] @superwhiskers  
- [ ] @ThatNerdyPikachu  
- [x] @SuperMarioDaBom  
- [ ] @lukeeey  
- [x] @CaramelKat

### CODE REVIEW

**Comment by superwhiskers** [comment]
i consent to having my contributions relicensed under the agplv3

**Comment by SuperMarioDaBom** [comment]
I give consent to my contributions being relicensed

**Comment by andreluis034** [comment]
I give consent to my contributions being relicensed

**Comment by mrjvs** [comment]
I give permission to change license to agpl3

**Comment by CaramelKat** [comment]
I give consent to my contributions being relicensed

**Comment by jonbarrow** [comment]
Upon further review the contributions made by @ThatNerdyPikachu are no longer in the codebase and the contributions made by @lukeeey only affected the README (which is also now gone apparently?). Moving forward with the license change

**Comment by lukeeey** [comment]
You don’t need my permission but you can have it anyway haha

**Pull request merged**
